app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
define('OMISE_PUBLIC_KEY', env('OMISE_PUBLIC', 'pkey_51jhypljyehiwle2wo4'));
define('OMISE_SECRET_KEY', env('OMISE_SECRET', 'skey_51jhyqi3ta12wrs5sn5'));
#Admin
$adminRoutes = function()
{
	Route::get('/','Admin\IndexController@index'); 
	Route::controllers([
		'auth' => 'Admin\Auth\AuthController', 
    'ga' => 'Admin\GaController' , 
	]);
	# global
	Route::resource('users', 'Admin\UsersController'); 
	Route::resource('vocabulary', 'Admin\VocabularyController'); 
	Route::get('/termdata/options/{vid}/{tid}', 'Admin\TermdataController@options');
  Route::resource('termdata', 'Admin\TermdataController');
  Route::get('filemanager', 'Admin\FilemanagerController@showIndex');   
  # 
  Route::resource('orders', 'Admin\OrdersController');
  Route::put('orders/{id}/changestatus','Admin\OrdersController@changestatus');
  
  Route::resource('products', 'Admin\ProductsController');
  Route::get('products/{id}/comments', 'Admin\ProductsController@comments');
  Route::get('products/{id}/comments/{cid}', 'Admin\ProductsController@commentedit');
  
  Route::resource('pages', 'Admin\PagesController');
  Route::get('pages/{id}/comments', 'Admin\PagesController@comments');
  Route::get('pages/{id}/comments/{cid}', 'Admin\PagesController@commentedit');  
  
  Route::resource('productimages','Admin\ProductImageController') ; 
  Route::resource('omises','Admin\OmisesController');
  Route::get('mandrill/info','Admin\MandrillController@info');
  Route::get('mandrill/url-lists','Admin\MandrillController@urlLists');
  
  Route::resource('comments', 'Admin\CommentsController'); 
  
  Route::get('ems/{ems}','Admin\EmsController@index') ; 
  
  Route::get('admindocs','Admin\AdmindocsController@index');
  Route::get('admindocs/{id}/{sefu}', 'Admin\AdmindocsController@view'); 
 
};

Route::group(array('domain' => 'admin.vichakorn.com'),$adminRoutes); 
Route::group(array('domain' => 'admin.vch.aecstar.com'),$adminRoutes);
Route::group(array('domain' => 'admin.luminancecocktail.com'),$adminRoutes);

#Page
Route::get('/', 'WelcomeController@index');  
Route::get('/home', 'HomeController@index');  
#Page - Abount US
Route::get('aboutus', 'AboutusController@index'); 
Route::get('aboutus/{sefu}', 'AboutusController@view'); 
#Page - Contact US
Route::get('contactus', 'ContactController@index'); 
Route::post('contactus','ContactController@submit');
#Page - Privileges
Route::get('privileges','PrivilegesController@index');
#Page - Order
Route::get('order','OrderController@index');
Route::post('order','OrderController@doOrder');
Route::get('order/comfirm-and-shipping','OrderController@confirm');
Route::post('order/comfirm-use-point' , 'OrderController@addPoint');
Route::post('order/comfirm-and-shipping','OrderController@doConfirm');
Route::get('order/payment','OrderController@payment');
Route::post('order/payment','OrderController@doPayment');
Route::get('order/cancel_paypal','OrderController@cancel_paypal');
Route::get('order/complete_paypal','OrderController@complete_paypal');
Route::post('order/ipn_paypal','OrderController@ipn_paypal');

Route::get('orders','OrdersController@index');
Route::get('orders/{id}','OrdersController@view');
#Page - Products 
Route::get('products','ProductsController@index');
Route::get('product/{sefu}', 'ProductsController@view'); 
#Page - Ordering and how to use
Route::get('ordering-and-how-to-use','HowtoController@index');
Route::get('ordering-and-how-to-use/{id}/{sefu}', 'HowtoController@view'); 
#Page - Wonders of use
Route::get('wonders-of-use','WonderController@index');
Route::get('wonders-of-use/{id}/{sefu}', 'WonderController@view'); 
#Page - Tricks and data inside 
Route::get('tricks-and-data-insight','TricksController@index');
Route::get('tricks-and-data-insight/{id}/{sefu}', 'TricksController@view'); 
#Page - Money Transfer ; 
Route::get('moneytransfer','TransferController@index') ; 
Route::post('moneytransfer','TransferController@doTransfer');
#HELPER - get ems ; 
Route::get('ems/{ems}','EmsController@index') ; 

Route::get('profile/edit', 'ProfileController@edit'); 
Route::post('profile/edit','ProfileController@update');

Route::resource('comments', 'CommentsController'); 

Route::get('historical-point', 'HistoricalPointController@index'); 

Route::controllers([
	'auth' => 'Auth\AuthController',
	'password' => 'Auth\PasswordController',
]);

app/User.php
<?php namespace App;

use Illuminate\Auth\Authenticatable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;
use LaravelBook\Ardent\Ardent;
use File;
use Image;
use Carbon ; 
use Session ; 

use App\Order;

class User extends Ardent implements AuthenticatableContract, CanResetPasswordContract {

	use Authenticatable, CanResetPassword;

	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */
	protected $table = 'users';

	/**
	 * The attributes that are mass assignable.
	 *
	 * @var array
	 */
	protected $fillable = ['name' , 'lastname' , 'username' , 'address', 'email', 'password','user_role_id'];

	/**
	 * The attributes excluded from the model's JSON form.
	 *
	 * @var array
	 */
	protected $hidden = ['password', 'remember_token'];
	
	protected $attachment = array( 
    'thumb' => array('w' => 100 , 'h' => 100 )
  ) ; 
    
  public static $rules = array(
  	'username' => 'required|unique:users',
  	'email' => 'required|email|unique:users',  
    'user_role_id' => 'required',
	);
	
	public static $relationsData = array(
        'role' => array(self::BELONGS_TO, 'App\Termdata', 'foreignKey' => 'user_role_id')  , 
        'orders' => array(self::HAS_MANY, 'App\Order' , 'user_id') ,     
    );
    
  /* --- Scope --- */
  
  public function scopeSearch($query,$q){
  	if(trim($q) == '')
  		return $query ;   
 		return $query->where(function($query) use ($q){ 
 			$query->where('name', 'LIKE' , '%'.$q.'%')
 				->orWhere('email', 'LIKE' , '%'.$q.'%')
 				->orWhere('phone', 'LIKE' , '%'.$q.'%')  ; 
 		}) ; 
  }
    
  public function scopeToken($query,$token){
  	return $query->where('token','=',$token);
  }
    
    /* ---- Attribute --- */
    
    
    public function isAdmin(){
        return $this->role->name == 'admin' ; 
    }
    
    public function shortname(){ 
        return ucfirst($this->name) . ' ' . strtoupper( substr($this->lastname,0,1)) . '.' ; 
    }
    
    public function avatarpath(){
    	if( $this->avatar == '')
    		return 'noavatar.png' ; 
    	return 'avatar/' . $this->id . '/thumb/' .  $this->avatar 	 ;
    }
    
    public function processAvatar(){
    	foreach($this->attachment as $key => $attach){ 
    		if(! File::exists(public_path() . '/images/avatar/' . $this->id . '/' . $key . '/'))
            	File::makeDirectory(public_path() . '/images/avatar/' . $this->id . '/' . $key . '/');
            $image = Image::make( public_path() . '/images/avatar/' . $this->id . '/' . $this->avatar )->fit($attach['w'],$attach['h'])->save( public_path() . '/images/avatar/' . $this->id . '/' . $key . '/' . $this->avatar);
        }
    }
    
    public function shipping($field){ 
    	$shipping = Session::get('shipping') ; 
    	if(isset($shipping[$field]))
    		return $shipping[$field] ; 
   		return $this->$field  ; 
    } 
    
    /*--- Attribute ---*/
    public function getShippingJsonAttribute(){
      $ret = array() ; 
      $ret['id'] = $this->id ; 
      $shipping = Session::get('shipping') ; 
      foreach($shipping as $k => $v){
        $ret[$k] = $v ; 
      }
      return json_encode($ret) ; 
    }
    
    public function getFullnameAttribute(){
        return $this->name . ' ' . $this->lastname ; 
    }
    
    public function getBirthDateFormattedAttribute(){
        return Carbon::createFromFormat('Y-m-d', $this->birthdate )->format('d/m/Y');
    }
    
    public function getUpdatedAtFormatAttribute(){ 
		$date = Carbon::createFromFormat('Y-m-d H:i:s', $this->updated_at  );
		$date->setTimezone('Asia/Bangkok');
		return $date->format('d/m/Y H:i:s');
    }
    
    public function getAddressHtmlAttribute(){
        return nl2br($this->address);
    }
    
    public function getTotalConfirmTransferAttribute(){
    	if(!$this->isAdmin())
    		return 0 ;
		return Order::hasStatus('transfer-reported')->count() ; 
    }
    
    public function getTotalConfirmAttribute(){
        if(!$this->isAdmin())
    		return 0 ;
		return Order::hasStatus('confirm')->count() ; 
    }
  

}

resources/views/about.blade.php
@extends('layouts.master')

@section('content')
<div class="row">
	<ol class="breadcrumb">
	  <li><a href="/">Home</a></li> 
	  <li><a href="{{ url('aboutus') }}">เกี่ยวกับเรา</a></li> 
	  <li class="active">{{$page->title}}</li>
	</ol>
</div>
<div class="row">
	<div class="col-md-4">
        <aside class="widget">
            <div class="widget-inner">
                <h3 class="widget-title" style="background-position: 0px -11px;">
                    <span>เกี่ยวกับเรา</span>
                </h3>
        		<ul class="left-menu list-unstyled">
        			@foreach($pages as $p)
        			<li @if($p->id == $page->id) class="active" @endif><a href="{{ URL::to('aboutus/'.$p->sefu) }}">{{$p->order}}. {{$p->title}}</a></li>
        			@endforeach
        		</ul>
            </div>
        </aside>
	</div>
	<div class="col-md-8">
		<h3>{{$page->order}}. {{$page->title}}</h3>
		{!!$page->body!!}
    @if($page->has_comments)
      <hr />
      @include('blocks.comments',['model' => $page , 'type' => 'App\Page' ])   
    @endif
	</div>
</div>
@stop

resources/views/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Laravel</title>

	<link href="{{ asset('/css/app.css') }}" rel="stylesheet">

	<!-- Fonts -->
	<link href='//fonts.googleapis.com/css?family=Roboto:400,300' rel='stylesheet' type='text/css'>

	<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
		<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
		<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->
</head>
<body>
	<nav class="navbar navbar-default">
		<div class="container-fluid">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
					<span class="sr-only">Toggle Navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="#">Laravel</a>
			</div>

			<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
				<ul class="nav navbar-nav">
					<li><a href="{{ url('/') }}">Home</a></li>
				</ul>

				<ul class="nav navbar-nav navbar-right">
					@if (Auth::guest())
						<li><a href="{{ url('/auth/login') }}">Login</a></li>
						<li><a href="{{ url('/auth/register') }}">Register</a></li>
					@else
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">{{ Auth::user()->name }} <span class="caret"></span></a>
							<ul class="dropdown-menu" role="menu">
								<li><a href="{{ url('/auth/logout') }}">Logout</a></li>
							</ul>
						</li>
					@endif
				</ul>
			</div>
		</div>
	</nav>

	@yield('content')

	<!-- Scripts -->
	<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
	<script src="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.1/js/bootstrap.min.js"></script>
</body>
</html>

resources/views/contact.blade.php
@extends('layouts.master')

@section('content')
<div class="row">
	<ol class="breadcrumb">
	  <li><a href="/">Home</a></li> 
	  <li class="active">ติดต่อเรา</li>
	</ol>
</div>
<div class="row"> 
	<div class="col-md-9">
		{!! $page->body !!} 
	</div>
	<div class="col-md-3">
		<br /><br />
		<div class="fb-page" data-href="https://www.facebook.com/luminancecocktail" data-width="100%" data-hide-cover="false" data-show-facepile="true" data-show-posts="false"><div class="fb-xfbml-parse-ignore"><blockquote cite="https://www.facebook.com/luminancecocktail"><a href="https://www.facebook.com/luminancecocktail">Luminance Cocktail</a></blockquote></div></div>
		<div class="row">
			<div class="col-lg-12">
				<h4>ติดต่อเรา</h4>
				{!! Notification::showAll() !!}
				@if (count($errors) > 0)
					<div class="alert alert-danger">
						<strong>ขออภัย</strong> เกิดปัญหาบางอย่างสำหรับข้อมูลที่ส่งมา<br><br>
						<ul>
							@foreach ($errors->all() as $error)
								<li>{{ $error }}</li>
							@endforeach
						</ul>
					</div>
				@endif
				{!! Form::open(array('url' => 'contactus' , 'role' => 'form' )) !!}
					<input type="hidden" name="_token" value="{{ csrf_token() }}">
					<div class="form-group">
					    <label for="email">Email address</label>
						<input type="email" class="form-control" id="email" name="email" placeholder="Email address" value="{{ old('email') }}"/>
					</div>
					<div class="form-group">
					    <label for="description">รายละเอียด</label>
					    <textarea class="form-control" id="description" name="description" placeholder="Decription" rows="8">{{ old('description') }}</textarea>
					</div> 
					<div class="form-group">
						{!! captcha_img() !!}
						<input type="text" class="form-control" id="captcha" name="captcha" placeholder="Captcha" value=""/>
					</div>
					<button type="submit" class="btn btn-primary">ส่งข้อความ</button>
					
				{!! Form::close() !!}
				<br /> 
			</div>
		</div>
		
	</div>
</div>
@stop

resources/views/home.blade.php
@extends('layouts.master')

@section('content')
<div class="row">
	<ol class="breadcrumb">
	  <li><a href="/">Home</a></li> 
	  <li class="active">ข้อมูลส่วนตัว</li>
	</ol>
</div>
<div class="row">
    <div class="col-md-2">
        <aside class="widget">
            <div class="widget-inner">
                <h3 class="widget-title" style="background-position: 0px -11px;">
                    <span>ข้อมูลส่วนตัว</span>
                </h3> 
                <img class="img-responsive img-rounded" src="/images/{{ Auth::user()->avatarpath() }}" />
                <ul class="left-menu list-unstyled">
                    <li class="active"><a href="/home">ข้อมูลส่วนตัว</a></li>
                    <li><a href="/orders">ประวัติการสั่งซื้อ</a></li>
                    <li><a href="/historical-point">ประวัติแต้มสะสม</a></li>
                </ul>
            </div>
        </aside>
    </div>
    <div class="col-md-10">
        <h2>ข้อมูลส่วนตัว <a href="{{ url('profile/edit') }}"><span class="glyphicon glyphicon-edit"></span> <small>(คลิกเพื่อแก้ไขข้อมูลส่วนตัว)</small></a></h2>
        {!! Notification::showAll() !!} 
        <table class="table table-striped">
            <tr>
                <td class="{{$table1}}">Username</td>
                <td class="{{$table2}}">{{ Auth::user()->username }}</td>
            </tr>
            <tr>
                <td class="{{$table1}}">Email</td>
                <td class="{{$table2}}">{{ Auth::user()->email }}</td>
            </tr>
            <tr>
                <td class="{{$table1}}">แต้มสะสม</td>
                <td class="{{$table2}}">{{ Auth::user()->point }}</td>
            </tr>
            <tr>
                <td class="{{$table1}}">ชื่อนามสกุล</td>
                <td class="{{$table2}}">{{ Auth::user()->fullname }}</td>
            </tr>
            <tr>
                <td class="{{$table1}}">เบอร์โทร</td>
                <td class="{{$table2}}">{{ Auth::user()->phone }}</td>
            </tr>
            <tr>
                <td class="{{$table1}}">เพศ</td>
                <td class="{{$table2}}">{{ Auth::user()->gender }}</td>
            </tr>
            <tr>
                <td class="{{$table1}}">วันเกิด</td>
                <td class="{{$table2}}">{{ Auth::user()->birthDateFormatted }}</td>
            </tr>
            <tr>
                <td class="{{$table1}}">ที่อยู่</td>
                <td class="{{$table2}}">{!! Auth::user()->addressHtml !!}</td>
            </tr>
            <tr>
                <td class="{{$table1}}">Facebook</td>
                <td class="{{$table2}}">{!! Auth::user()->facebookname !!}</td>
            </tr>
            <tr>
                <td class="{{$table1}}">Line ID</td>
                <td class="{{$table2}}">{!! Auth::user()->lineid !!}</td>
            </tr>
            <tr>
                <td class="{{$table1}}">รับข่าวสารทางอีเมล์</td>
                <td class="{{$table2}}">
                    @if(Auth::user()->is_subscribe)
                        ใช่
                    @else
                        ไม่
                    @endif
                </td>
            </tr>
            
        </table>
    </div>
</div>
@stop

resources/views/howto.blade.php
@extends('layouts.master')

@section('content')
<div class="row">
	<ol class="breadcrumb">
	  <li><a href="/">Home</a></li> 
	  <li><a href="{{ url('ordering-and-how-to-use') }}">ลำดับและวิธีการใช้ผลิตภัณฑ์</a></li> 
	  <li class="active">{{$page->title}}</li>
	</ol>
</div>
<div class="row">
	<div class="col-md-4">
        <aside class="widget">
            <div class="widget-inner">
                <h3 class="widget-title" style="background-position: 0px -11px;">
                    <span>ลำดับและวิธีการใช้ผลิตภัณฑ์</span>
                </h3>
        		<ul class="left-menu list-unstyled">
        			@foreach($pages as $p)
        			<li @if($p->id == $page->id) class="active" @endif><a href="{{ URL::to('ordering-and-how-to-use/'.$p->id.'/'.$p->sefu) }}">{{$p->order}}. {{$p->title}}</a></li>
        			@endforeach
        		</ul>
            </div>
        </aside>
	</div>
	<div class="col-md-8">
		<h3>{{$page->order}}. {{$page->title}}</h3>
		{!!$page->body!!}
    @if($page->has_comments)
      <hr />
      @include('blocks.comments',['model' => $page , 'type' => 'App\Page' ])   
    @endif
	</div>
</div>
@stop

resources/views/point.blade.php
@extends('layouts.master')

@section('content')
<div class="row">
	<ol class="breadcrumb">
	  <li><a href="/">Home</a></li> 
	  <li class="active">ประวัติแต้มสะสม</li>
	</ol>
</div>
<div class="row">
    <div class="col-md-2">
        <aside class="widget">
            <div class="widget-inner">
                <h3 class="widget-title" style="background-position: 0px -11px;">
                    <span>ข้อมูลส่วนตัว</span>
                </h3> 
                <img class="img-responsive img-rounded" src="/images/{{ Auth::user()->avatarpath() }}" />
                <ul class="left-menu list-unstyled">
                    <li><a href="/home">ข้อมูลส่วนตัว</a></li>
                    <li><a href="/orders">ประวัติการสั่งซื้อ</a></li>
                    <li class="active"><a href="/historical-point">ประวัติแต้มสะสม</a></li>
                </ul>
            </div>
        </aside>
    </div>
    <div class="col-md-10"> 
      <h3>คุณมีคะแนนคงเหลือทั้งสิ้น  {{Auth::user()->point}} แต้ม</h3> 
      <table class="table-striped table">
        <thead>
          <th>วันที่</th>
          <th>หมายเลข Order</th>
          <th>รายละเอียด</th>
          <th class="text-right">แต้ม</th>
        </thead>
        <tbody>
          @foreach($records as $record )
          <tr>
            <td>{{$record->createdAtFormat }}</td>
            <td>
              @if(is_null($record->order) == false )
                <a href="{{ url('/orders/' . $record->order->id) }}">#{{ $record->order->orderNumber }}</a>
              @endif  
            </td>
            <td>{{$record->remark}}</td>
            <td class="text-right">{{$record->point}}</td>
          </tr>
          @endforeach
          <tr>
            <td colspan="3"><strong>คะแนนคงเหลือ</strong></td>
            <td class="text-right"><strong>{{Auth::user()->point}}</strong></td>
          </tr>
        </tbody>
      </table>
      <div class="text-center">
    		<?php echo $records->render(); ?>
    	</div>
    </div>
</div>
@stop

resources/views/privileges.blade.php
@extends('layouts.master')

@section('content')
<div class="row">
	<ol class="breadcrumb">
	  <li><a href="/">Home</a></li> 
	  <li class="active">สิทธิพิเศษสมาชิก</li>
	</ol>
</div>
<div class="row"> 
	<div class="col-md-9">
		{!! $page->body !!}
		<br />
		@if(Auth::guest())
		<div class="row">
			<div class="col-sm-offset-4 col-sm-4 col-xs-offset-3 col-xs-6">
			<a href="/auth/register" class="btn btn-primary form-control">สมัครสมาชิก คลิ๊กที่นี่</a>
			</div>
		 </div>
		@endif
	</div>
	<div class="col-xs-3">
		<br /><br />
		<div class="fb-page" data-href="https://www.facebook.com/luminancecocktail" data-width="100%" data-hide-cover="false" data-show-facepile="true" data-show-posts="false"><div class="fb-xfbml-parse-ignore"><blockquote cite="https://www.facebook.com/luminancecocktail"><a href="https://www.facebook.com/luminancecocktail">Luminance Cocktail</a></blockquote></div></div>
	</div>
</div>
@stop

resources/views/tricks.blade.php
@extends('layouts.master')

@section('content')
<div class="row">
	<ol class="breadcrumb">
	  <li><a href="/">Home</a></li> 
	  <li><a href="{{ url('tricks-and-data-insight') }}">นานาสาระและข้อมูลความรู้เชิงลึก</a></li> 
	  <li class="active">{{$page->title}}</li>
	</ol>
</div>
<div class="row">
	<div class="col-md-4">
        <aside class="widget">
            <div class="widget-inner">
                <h3 class="widget-title" style="background-position: 0px -11px;">
                    <span>นานาสาระและข้อมูลความรู้เชิงลึก</span>
                </h3>
        		<ul class="left-menu list-unstyled">
        			@foreach($pages as $p)
        			<li @if($p->id == $page->id) class="active" @endif><a href="{{ URL::to('tricks-and-data-insight/'.$p->id.'/'.$p->sefu) }}">{{$p->order}}. {{$p->title}}</a></li>
        			@endforeach
        		</ul>
            </div>
        </aside>
	</div>
	<div class="col-md-8">
		<h3>{{$page->order}}. {{$page->title}}</h3>
		{!!$page->body!!}
    @if($page->has_comments)
      <hr />
      @include('blocks.comments',['model' => $page , 'type' => 'App\Page' ])   
    @endif
	</div>
</div>
@stop

resources/views/wonder.blade.php
@extends('layouts.master')

@section('content')
<div class="row">
	<ol class="breadcrumb">
	  <li><a href="/">Home</a></li> 
	  <li><a href="{{ url('wonders-of-use') }}">มหัศจรรย์แห่งการใช้ผลิตภัณฑ์  Luminance Cocktail ครบเซ็ต</a></li> 
	  <li class="active">{{$page->title}}</li>
	</ol>
</div>
<div class="row">
	<div class="col-md-4">
        <aside class="widget">
            <div class="widget-inner">
                <h3 class="widget-title" style="background-position: 0px -11px;">
                    <span>มหัศจรรย์แห่งการใช้ผลิตภัณฑ์ Luminance Cocktail ครบเซ็ต</span>
                </h3>
        		<ul class="left-menu list-unstyled">
        			@foreach($pages as $p)
        			<li @if($p->id == $page->id) class="active" @endif><a href="{{ URL::to('wonders-of-use/'.$p->id.'/'.$p->sefu) }}">{{$p->order}}. {{$p->title}}</a></li>
        			@endforeach
        		</ul>
            </div>
        </aside>
	</div>
	<div class="col-md-8">
		<h3>{{$page->order}}. {{$page->title}}</h3>
		{!!$page->body!!}
    @if($page->has_comments)
      <hr />
      @include('blocks.comments',['model' => $page , 'type' => 'App\Page' ])   
    @endif
	</div>
</div>
@stop